[workspace]
members = [
	"src/himmelblaud",
	"src/unix_common",
	"src/msal",
	"src/pam",
	"src/nss"
]

[workspace.package]
version = "0.1.0"
authors = [
    "David Mulder <dmulder@suse.com>"
]
rust-version = "1.66"
edition = "2021"
license = "MPL-2.0"
homepage = "https://codeberg.org/dmulder/himmelblau/"
repository = "https://codeberg.org/dmulder/himmelblau/"

[workspace.dependencies]
libc = "^0.2.144"
pkg-config = "^0.3.27"
lazy_static = "^1.4.0"
paste = "^1.0.12"
serde = { version = "^1.0.163", features = ["derive"] }
serde_json = "^1.0.96"
log = "^0.4.17"
himmelblau_unix_common = { version = "^0.1.0", path = "src/unix_common" }
msal = { version = "^0.1.0", path = "src/msal" }
