[package]
name = "himmelblau_unix_common"

version.workspace = true
authors.workspace = true
rust-version.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[lib]
name = "himmelblau_unix_common"
path = "src/lib.rs"

[dependencies]
serde = { workspace = true }
serde-pickle = "^1.1.1"
serde_derive = "^1.0.164"
serde_json = { workspace = true }
tracing = { workspace = true }
configparser = "^3.0.2"
msal = { workspace = true }
rand = "^0.8"
rand_chacha = "^0.3"
