[package]
name = "himmelblaud"
description = "Himmelblau Authentication Daemon"

version.workspace = true
authors.workspace = true
rust-version.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[[bin]]
name = "himmelblaud"
path = "src/daemon.rs"

[[bin]]
name = "himmelblaud_tasks"
path = "src/tasks_daemon.rs"

[dependencies]
himmelblau_unix_common = { workspace = true }
tokio = { workspace = true }
tokio-util = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
clap = { workspace = true }
bytes = "^1.3.0"
serde = { workspace = true }
serde_json = { workspace = true }
futures = "^0.3.28"
systemd-journal-logger = "^2.1.1"
himmelblau_policies = { workspace = true }
users = "^0.11.0"
sketching = { workspace = true }
walkdir = { workspace = true }
libc = { workspace = true }
kanidm_utils_users = { workspace = true }
csv = { workspace = true }
notify-debouncer-full = { workspace = true }
kanidm-hsm-crypto = { workspace = true }
