[package]
name = "pam_himmelblau"
links = "pam"

version.workspace = true
authors.workspace = true
rust-version.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[lib]
name = "pam_himmelblau"
crate-type = [ "cdylib" ]

[dependencies]
libc = { workspace = true }
kanidm_unix_common = { workspace = true }
tracing-subscriber = { workspace = true }
tracing = { workspace = true }

[build-dependencies]
pkg-config.workspace = true
